SET SQL DIALECT 3;


CREATE GENERATOR GEN_TAB_LOTE_AVES_ID;

CREATE TABLE TAB_LOTE_AVES (
    ID_LOTE             INTEGER NOT NULL,
    DESCRICAO           VARCHAR(100),
    DATA_ENTRADA        DATE,
    QUANTIDADE_INICIAL  INTEGER
);

ALTER TABLE TAB_LOTE_AVES ADD CONSTRAINT PK_TAB_LOTE_AVES PRIMARY KEY (ID_LOTE);


SET TERM ^ ;


CREATE OR ALTER TRIGGER TAB_LOTE_AVES_BI FOR TAB_LOTE_AVES
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id_lote is null) then
    new.id_lote = gen_id(gen_tab_lote_aves_id,1);
end
^


SET TERM ; ^