SET SQL DIALECT 3;


CREATE GENERATOR GEN_TAB_MORTALIDADE_ID;

CREATE TABLE TAB_MORTALIDADE (
    ID_MORTALIDADE    INTEGER NOT NULL,
    ID_LOTE_FK        INTEGER,
    DATA_MORTALIDADE  DATE,
    QUANTIDADE_MORTA  INTEGER,
    OBSERVACAO        VARCHAR(255)
);

ALTER TABLE TAB_MORTALIDADE ADD CONSTRAINT PK_TAB_MORTALIDADE PRIMARY KEY (ID_MORTALIDADE);

ALTER TABLE TAB_MORTALIDADE ADD CONSTRAINT FK_TAB_MORTALIDADE_1 FOREIGN KEY (ID_LOTE_FK) REFERENCES TAB_LOTE_AVES (ID_LOTE) ON DELETE CASCADE;


SET TERM ^ ;


CREATE OR ALTER TRIGGER TAB_MORTALIDADE_BI FOR TAB_MORTALIDADE
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id_mortalidade is null) then
    new.id_mortalidade = gen_id(gen_tab_mortalidade_id,1);
end
^


SET TERM ; ^