SET SQL DIALECT 3;


CREATE GENERATOR GEN_TAB_PESAGEM_ID;

CREATE TABLE TAB_PESAGEM (
    ID_PESAGEM         INTEGER NOT NULL,
    ID_LOTE_FK         INTEGER,
    DATA_PESAGEM       DATE,
    PESO_MEDIO         DECIMAL(15,2),
    QUANTIDADE_PESADA  INTEGER
);

ALTER TABLE TAB_PESAGEM ADD CONSTRAINT PK_TAB_PESAGEM PRIMARY KEY (ID_PESAGEM);

ALTER TABLE TAB_PESAGEM ADD CONSTRAINT FK_TAB_PESAGEM_1 FOREIGN KEY (ID_LOTE_FK) REFERENCES TAB_LOTE_AVES (ID_LOTE) ON DELETE CASCADE;


SET TERM ^ ;


CREATE OR ALTER TRIGGER TAB_PESAGEM_BI FOR TAB_PESAGEM
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id_pesagem is null) then
    new.id_pesagem = gen_id(gen_tab_pesagem_id,1);
end
^


SET TERM ; ^