SET TERM ^ ;

create or alter procedure SP_INSERIR_LOTE (
    PDESCRICAO varchar(100),
    PDATA_ENTRADA date,
    PQTD_INICIAL integer)
as
BEGIN
    IF (PQTD_INICIAL <= 0) THEN
        EXCEPTION EX_QTD_INVALIDA;

    INSERT INTO TAB_LOTE_AVES (
        DESCRICAO,
        DATA_ENTRADA,
        QUANTIDADE_INICIAL
    )
    VALUES (
        :PDESCRICAO,
        :PDATA_ENTRADA,
        :PQTD_INICIAL
    );
END^

SET TERM ; ^

GRANT INSERT ON TAB_LOTE_AVES TO PROCEDURE SP_INSERIR_LOTE;

GRANT EXECUTE ON PROCEDURE SP_INSERIR_LOTE TO SYSDBA;