SET TERM ^ ;

create or alter procedure SP_INSERIR_MORTALIDADE (
    PID_LOTE integer,
    PDATA date,
    PQTD integer,
    POBS varchar(255))
returns (
    PPERCENTUAL numeric(10,2))
as
declare variable V_QTD_INICIAL integer;
declare variable V_TOTAL_MORTO integer;
BEGIN
    SELECT QUANTIDADE_INICIAL
    FROM TAB_LOTE_AVES
    WHERE ID_LOTE = :PID_LOTE
    INTO :V_QTD_INICIAL;

    SELECT COALESCE(SUM(QUANTIDADE_MORTA),0)
    FROM TAB_MORTALIDADE
    WHERE ID_LOTE_FK = :PID_LOTE
    INTO :V_TOTAL_MORTO;

    IF ((:V_TOTAL_MORTO + :PQTD) > :V_QTD_INICIAL) THEN
        EXCEPTION EX_QTD_MORTALIDADE;

    INSERT INTO TAB_MORTALIDADE (
        ID_LOTE_FK,
        DATA_MORTALIDADE,
        QUANTIDADE_MORTA,
        OBSERVACAO
    )
    VALUES (
        :PID_LOTE,
        :PDATA,
        :PQTD,
        :POBS
    );

    V_TOTAL_MORTO = V_TOTAL_MORTO + :PQTD;
    PPERCENTUAL = (V_TOTAL_MORTO * 100.0) / V_QTD_INICIAL;

    SUSPEND;
END^

SET TERM ; ^

GRANT SELECT ON TAB_LOTE_AVES TO PROCEDURE SP_INSERIR_MORTALIDADE;
GRANT SELECT,INSERT ON TAB_MORTALIDADE TO PROCEDURE SP_INSERIR_MORTALIDADE;

GRANT EXECUTE ON PROCEDURE SP_INSERIR_MORTALIDADE TO SYSDBA;