SET TERM ^ ;

create or alter procedure SP_INSERIR_PESAGEM (
    PID_LOTE integer,
    PDATA date,
    PPESO_MEDIO numeric(10,2),
    PQTD integer)
as
declare variable V_QTD_INICIAL integer;
declare variable V_TOTAL_PESADO integer;
BEGIN
    SELECT QUANTIDADE_INICIAL
    FROM TAB_LOTE_AVES
    WHERE ID_LOTE = :PID_LOTE
    INTO :V_QTD_INICIAL;

    SELECT COALESCE(SUM(QUANTIDADE_PESADA),0)
    FROM TAB_PESAGEM
    WHERE ID_LOTE_FK = :PID_LOTE
    INTO :V_TOTAL_PESADO;

    IF ((:V_TOTAL_PESADO + :PQTD) > :V_QTD_INICIAL) THEN
        EXCEPTION EX_QTD_PESAGEM;

    INSERT INTO TAB_PESAGEM (
        ID_LOTE_FK,
        DATA_PESAGEM,
        PESO_MEDIO,
        QUANTIDADE_PESADA
    )
    VALUES (
        :PID_LOTE,
        :PDATA,
        :PPESO_MEDIO,
        :PQTD
    );
END^

SET TERM ; ^

GRANT SELECT ON TAB_LOTE_AVES TO PROCEDURE SP_INSERIR_PESAGEM;
GRANT SELECT,INSERT ON TAB_PESAGEM TO PROCEDURE SP_INSERIR_PESAGEM;

GRANT EXECUTE ON PROCEDURE SP_INSERIR_PESAGEM TO SYSDBA;